---
on:
    push:
        branches:
            - main
    pull_request:

name: Continuous integration

jobs:
    test:
        name: Test suite
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2.4.0
              with:
                  submodules: true
            - uses: actions-rs/toolchain@v1.0.7
              with:
                  profile: minimal
                  toolchain: stable
                  override: true
                  components: clippy, rustfmt
            - uses: Swatinem/rust-cache@v1
            - name: Check formatting
              uses: actions-rs/cargo@v1.0.3
              with:
                  command: fmt
                  args: -- --check
            - name: Clippy
              uses: actions-rs/cargo@v1.0.3
              env:
                  RUSTFLAGS: -Dwarnings
              with:
                  command: clippy
            - name: Build and test
              uses: actions-rs/cargo@v1.0.3
              with:
                  command: test
